package generate

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/carlosframework/rastrillo"
)

// newActionsAppRoot builds an app root with just enough of a go.mod for
// actionsModulePath to resolve a module path — EmitActions needs one to
// build the store package's import path, unlike EmitStore/EmitTemplates
// which never emit Go import statements.
func newActionsAppRoot(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module scratch\n\ngo 1.25.0\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// goldenIndexGETGo is EmitActions' output for the fixture's index.GET
// (List): Search + one Filter (Title) declared, so both the search box
// and the filter's query param round-trip through the store's Params
// structs; Rows come from List.Columns[0]/[1] (Title/Price, Price
// formatted through formatCents); pagination has no gap-collapsing
// (every page number renders — a v1 simplification, see the report).
const goldenIndexGETGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_notes_index_get

import (
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/carlosframework/rastrillo"
	notesstore "scratch/gen/store/notes"
)

// Handle is GET /admin/notes.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	search := strings.TrimSpace(r.URL.Query().Get("q"))
	filterTitle := r.URL.Query().Get("title")

	page := 1
	if v := r.URL.Query().Get("page"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			page = n
		}
	}
	const pageSize = 10
	offset := (page - 1) * pageSize

	var carry [][2]string
	if filterTitle != "" {
		carry = append(carry, [2]string{"title", filterTitle})
	}

	store := notesstore.New(ctx.DB)
	total, err := store.CountNotes(r.Context(), notesstore.CountNotesParams{
		Search:      search,
		FilterTitle: filterTitle,
	})
	if err != nil {
		fail(ctx, w, "counting notes", err)
		return
	}
	rows, err := store.ListNotes(r.Context(), notesstore.ListNotesParams{
		Search:      search,
		FilterTitle: filterTitle,
		PageOffset:  int64(offset),
		PageLimit:   pageSize,
	})
	if err != nil {
		fail(ctx, w, "loading notes", err)
		return
	}

	items := make([]listRow, 0, len(rows))
	for _, n := range rows {
		items = append(items, listRow{
			Href: fmt.Sprintf("/admin/notes/%d", n.ID),
			Main: n.Title,
			Sub:  formatCents(n.Price),
		})
	}

	totalPages := (int(total) + pageSize - 1) / pageSize
	show := int(total) > pageSize
	var pageItems []listPageItem
	if show {
		prev := listPageItem{Label: "Previous", Disabled: true}
		if page > 1 {
			prev = listPageItem{Label: "Previous", Href: href(search, carry, page-1)}
		}
		pageItems = append(pageItems, prev)
		for n := 1; n <= totalPages; n++ {
			if n == page {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Current: true})
			} else {
				pageItems = append(pageItems, listPageItem{Label: strconv.Itoa(n), Href: href(search, carry, n)})
			}
		}
		next := listPageItem{Label: "Next", Disabled: true}
		if page < totalPages {
			next = listPageItem{Label: "Next", Href: href(search, carry, page+1)}
		}
		pageItems = append(pageItems, next)
	}

	render(ctx, w, "notes/list", http.StatusOK, listView{
		Empty:      total == 0,
		Query:      search,
		Carry:      carry,
		Rows:       items,
		Pagination: listPagination{Show: show, Items: pageItems},
	})
}

// href builds one list/pagination link, preserving the current search
// and filter values and setting page.
func href(search string, carry [][2]string, page int) string {
	var params []string
	if search != "" {
		params = append(params, "q="+url.QueryEscape(search))
	}
	for _, kv := range carry {
		params = append(params, kv[0]+"="+url.QueryEscape(kv[1]))
	}
	params = append(params, "page="+strconv.Itoa(page))
	return "/admin/notes" + "?" + strings.Join(params, "&")
}

type listView struct {
	Empty      bool
	Query      string
	Carry      [][2]string
	Rows       []listRow
	Pagination listPagination
}

type listRow struct {
	Href string
	Main string
	Sub  string
}

type listPagination struct {
	Show  bool
	Items []listPageItem
}

type listPageItem struct {
	Label    string
	Href     string
	Current  bool
	Disabled bool
	Gap      bool
}

// fail logs through Ctx.Logger (when set) and answers a plain 500.
func fail(ctx *rastrillo.Ctx, w http.ResponseWriter, what string, err error) {
	if ctx.Logger != nil {
		ctx.Logger.Error("notes: "+what, "err", err)
	}
	http.Error(w, "Something went wrong.", http.StatusInternalServerError)
}

// render hands data to the app's template tree through ctx.Render (see
// rastrillo.Ctx's Render field) — a 500 with a clear log line stands in
// for a template an app forgot to wire, rather than a nil-pointer panic.
func render(ctx *rastrillo.Ctx, w http.ResponseWriter, page string, status int, data any) {
	if ctx.Render == nil {
		if ctx.Logger != nil {
			ctx.Logger.Error("notes: " + "Ctx.Render is nil; the app's ctx factory must set it")
		}
		http.Error(w, "Something went wrong.", http.StatusInternalServerError)
		return
	}
	ctx.Render(ctx, w, page, status, data)
}

// parseID reads the {id} path value. A non-numeric id is a URL that
// was never ours, so the caller answers 404 rather than 400.
func parseID(r *http.Request) (int64, bool) {
	id, err := strconv.ParseInt(r.PathValue("id"), 10, 64)
	if err != nil || id < 1 {
		return 0, false
	}
	return id, true
}

// formatCents renders cents as a dollar string — the only money
// formatting a generated template ever sees; a template never does
// money math itself.
func formatCents(cents int64) string {
	return fmt.Sprintf("$%d.%02d", cents/100, cents%100)
}

// parseCents parses a decimal-dollars string (e.g. "12.34") into
// cents, rejecting more than two decimal places. An empty string
// parses to zero cents, not an error — v1 has no server-side
// required-field validation.
func parseCents(s string) (int64, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0, nil
	}
	neg := false
	if strings.HasPrefix(s, "-") {
		neg = true
		s = s[1:]
	}
	whole, frac, hasFrac := strings.Cut(s, ".")
	if hasFrac && len(frac) > 2 {
		return 0, fmt.Errorf("enter a dollar amount with at most 2 decimal places")
	}
	for len(frac) < 2 {
		frac += "0"
	}
	if whole == "" {
		whole = "0"
	}
	wholeN, err := strconv.ParseInt(whole, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("enter a valid dollar amount")
	}
	fracN, err := strconv.ParseInt(frac, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("enter a valid dollar amount")
	}
	cents := wholeN*100 + fracN
	if neg {
		cents = -cents
	}
	return cents, nil
}
`

// goldenEditBasicsPOSTGo is EmitActions' output for the fixture's
// [id]/edit-basics.POST: Form.Basics is Title (Text) and Body
// (Textarea) — no Money field in this group at all, so no validation
// branch is emitted (generation time already knows no parse here can
// fail; see the package doc). The existence Get is still present
// (Get-or-404 before ever attempting the UPDATE), its result just
// discarded.
const goldenEditBasicsPOSTGo = `// Code generated by rastrillo generate. DO NOT EDIT.

package act_admin_notes_id_edit_basics_post

import (
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/carlosframework/rastrillo"
	notesstore "scratch/gen/store/notes"
)

// Handle is POST /admin/notes/{id}/edit-basics.
func Handle(ctx *rastrillo.Ctx, w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad request.", http.StatusBadRequest)
		return
	}
	id, ok := parseID(r)
	if !ok {
		http.NotFound(w, r)
		return
	}
	store := notesstore.New(ctx.DB)
	_, err := store.GetNote(r.Context(), id)
	if errors.Is(err, sql.ErrNoRows) {
		http.NotFound(w, r)
		return
	}
	if err != nil {
		fail(ctx, w, "loading notes", err)
		return
	}

	vTitle := strings.TrimSpace(r.PostFormValue("Title"))
	vBody := r.PostFormValue("Body")

	now := time.Now().UTC().Format(time.RFC3339)
	if err := store.UpdateNoteBasics(r.Context(), notesstore.UpdateNoteBasicsParams{
		Title: vTitle,
		Body:  vBody,
		Now:   now,
		ID:    id,
	}); err != nil {
		fail(ctx, w, "updating notes", err)
		return
	}
	http.Redirect(w, r, fmt.Sprintf("/admin/notes/%d", id), http.StatusSeeOther)
}

// fail logs through Ctx.Logger (when set) and answers a plain 500.
func fail(ctx *rastrillo.Ctx, w http.ResponseWriter, what string, err error) {
	if ctx.Logger != nil {
		ctx.Logger.Error("notes: "+what, "err", err)
	}
	http.Error(w, "Something went wrong.", http.StatusInternalServerError)
}

// render hands data to the app's template tree through ctx.Render (see
// rastrillo.Ctx's Render field) — a 500 with a clear log line stands in
// for a template an app forgot to wire, rather than a nil-pointer panic.
func render(ctx *rastrillo.Ctx, w http.ResponseWriter, page string, status int, data any) {
	if ctx.Render == nil {
		if ctx.Logger != nil {
			ctx.Logger.Error("notes: " + "Ctx.Render is nil; the app's ctx factory must set it")
		}
		http.Error(w, "Something went wrong.", http.StatusInternalServerError)
		return
	}
	ctx.Render(ctx, w, page, status, data)
}

// parseID reads the {id} path value. A non-numeric id is a URL that
// was never ours, so the caller answers 404 rather than 400.
func parseID(r *http.Request) (int64, bool) {
	id, err := strconv.ParseInt(r.PathValue("id"), 10, 64)
	if err != nil || id < 1 {
		return 0, false
	}
	return id, true
}

// formatCents renders cents as a dollar string — the only money
// formatting a generated template ever sees; a template never does
// money math itself.
func formatCents(cents int64) string {
	return fmt.Sprintf("$%d.%02d", cents/100, cents%100)
}

// parseCents parses a decimal-dollars string (e.g. "12.34") into
// cents, rejecting more than two decimal places. An empty string
// parses to zero cents, not an error — v1 has no server-side
// required-field validation.
func parseCents(s string) (int64, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0, nil
	}
	neg := false
	if strings.HasPrefix(s, "-") {
		neg = true
		s = s[1:]
	}
	whole, frac, hasFrac := strings.Cut(s, ".")
	if hasFrac && len(frac) > 2 {
		return 0, fmt.Errorf("enter a dollar amount with at most 2 decimal places")
	}
	for len(frac) < 2 {
		frac += "0"
	}
	if whole == "" {
		whole = "0"
	}
	wholeN, err := strconv.ParseInt(whole, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("enter a valid dollar amount")
	}
	fracN, err := strconv.ParseInt(frac, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("enter a valid dollar amount")
	}
	cents := wholeN*100 + fracN
	if neg {
		cents = -cents
	}
	return cents, nil
}
`

func TestEmitActionsGoldenFiles(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := fixtureResource()

	written, skipped, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}
	if len(skipped) != 0 {
		t.Fatalf("skipped = %v, want none", skipped)
	}
	wantWritten := []string{
		filepath.Join(genDir, "actions", "admin", "notes", "index_get", "index.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "index_post", "index.POST.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "new_get", "new.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "index_get", "index.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_get", "edit.GET.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_basics_post", "edit-basics.POST.go"),
		filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_advanced_post", "edit-advanced.POST.go"),
	}
	if len(written) != len(wantWritten) {
		t.Fatalf("written = %v, want %v", written, wantWritten)
	}
	for i := range wantWritten {
		if written[i] != wantWritten[i] {
			t.Errorf("written[%d] = %q, want %q", i, written[i], wantWritten[i])
		}
	}

	cases := []struct{ path, want string }{
		{filepath.Join(genDir, "actions", "admin", "notes", "index_get", "index.GET.go"), goldenIndexGETGo},
		{filepath.Join(genDir, "actions", "admin", "notes", "id", "edit_basics_post", "edit-basics.POST.go"), goldenEditBasicsPOSTGo},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}
}

func TestEmitActionsIsIdempotent(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := fixtureResource()

	written, _, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions (1st): %v", err)
	}
	first := readAllFiles(t, written)

	if _, _, err := EmitActions(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitActions (2nd): %v", err)
	}
	second := readAllFiles(t, written)

	for _, p := range written {
		if first[p] != second[p] {
			t.Errorf("%s changed between runs", p)
		}
	}
}

func TestEmitActionsSkipsHandWrittenFile(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := fixtureResource()

	handDir := filepath.Join(appRoot, "actions", "admin", "notes")
	if err := os.MkdirAll(handDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(handDir, "index.GET.go"), []byte("hand-written"), 0o644); err != nil {
		t.Fatal(err)
	}

	written, skipped, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}

	wantSkipped := filepath.Join(genDir, "actions", "admin", "notes", "index_get", "index.GET.go")
	if len(skipped) != 1 || skipped[0] != wantSkipped {
		t.Fatalf("skipped = %v, want [%s]", skipped, wantSkipped)
	}
	if len(written) != 6 {
		t.Fatalf("written = %v, want 6 files (index.GET skipped)", written)
	}
	for _, w := range written {
		if w == wantSkipped {
			t.Errorf("skipped path %s also present in written", wantSkipped)
		}
	}
	if _, err := os.Stat(wantSkipped); !os.IsNotExist(err) {
		t.Errorf("skipped file %s was written to gen/ anyway", wantSkipped)
	}
}

// noAdvancedFixtureResource is fixtureResource with an empty
// Form.Advanced — exercises the path where edit-advanced.POST must not
// be emitted at all.
func noAdvancedFixtureResource() rastrillo.Resource {
	r := rastrillo.Resource{
		Name:  "widgets",
		Route: "/admin/widgets",
		Store: rastrillo.Exclusive,
		List: rastrillo.List{
			Columns: []rastrillo.Column{{Field: "Name"}},
		},
		Form: rastrillo.Form{
			Basics: []rastrillo.Field{{Name: "Name"}},
		},
	}
	if err := r.Validate(); err != nil {
		panic(err)
	}
	return r
}

func TestEmitActionsOmitsEditAdvancedWhenNoAdvancedFields(t *testing.T) {
	appRoot := newActionsAppRoot(t)
	genDir := t.TempDir()
	r := noAdvancedFixtureResource()

	written, skipped, err := EmitActions(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitActions: %v", err)
	}
	if len(skipped) != 0 {
		t.Fatalf("skipped = %v, want none", skipped)
	}
	if len(written) != 6 {
		t.Fatalf("written = %v, want exactly 6 files (no edit-advanced.POST)", written)
	}
	for _, w := range written {
		if strings.Contains(w, "edit_advanced") {
			t.Errorf("written contains an edit-advanced file for a resource with no Advanced fields: %s", w)
		}
	}
}

// ── Compile test ─────────────────────────────────────────────────────
//
// stubNotesStore mirrors the real sqlc output for the fixture resource
// exactly (verified by hand against a real `go tool sqlc generate` run
// during development — see the report): DBTX/New/Queries, the Note
// row struct, and every query method/Params struct EmitActions'
// generated Handle functions call. Using a hand-written stub rather
// than shelling out to sqlc keeps this test fast and network-free;
// TestRunSqlcGeneratesCompilingStore (sqlcrun_test.go) is what proves
// the real sqlc output matches this shape.
const stubNotesStore = `package notesstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Note struct {
	ID        int64
	Title     string
	Price     int64
	Body      string
	CreatedAt string
	UpdatedAt string
}

type ListNotesParams struct {
	Search      interface{}
	FilterTitle interface{}
	PageOffset  int64
	PageLimit   int64
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	return nil, nil
}

type CountNotesParams struct {
	Search      interface{}
	FilterTitle interface{}
}

func (q *Queries) CountNotes(ctx context.Context, arg CountNotesParams) (int64, error) {
	return 0, nil
}

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	return Note{}, nil
}

type CreateNoteParams struct {
	Title string
	Price int64
	Body  string
	Now   string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (int64, error) {
	return 0, nil
}

type UpdateNoteBasicsParams struct {
	Title string
	Body  string
	Now   string
	ID    int64
}

func (q *Queries) UpdateNoteBasics(ctx context.Context, arg UpdateNoteBasicsParams) error {
	return nil
}

type UpdateNoteAdvancedParams struct {
	Price int64
	Now   string
	ID    int64
}

func (q *Queries) UpdateNoteAdvanced(ctx context.Context, arg UpdateNoteAdvancedParams) error {
	return nil
}
`

// stubWidgetsStore is the second resource's stub: List.Search false,
// no Filter — the opposite corner of the generation-time gates from
// notes (which has both), so the two fixtures together exercise every
// Search/Filter/Advanced combination this task's gates branch on.
const stubWidgetsStore = `package widgetsstore

import "context"

type DBTX interface{}

func New(db DBTX) *Queries { return &Queries{db: db} }

type Queries struct{ db DBTX }

type Widget struct {
	ID        int64
	Name      string
	CreatedAt string
	UpdatedAt string
}

type ListWidgetsParams struct {
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListWidgets(ctx context.Context, arg ListWidgetsParams) ([]Widget, error) {
	return nil, nil
}

// CountWidgets takes no Params struct at all — verified against a
// real sqlc generate run: a query with zero bind parameters (widgets
// has neither Search nor a declared Filter) drops the arg entirely
// rather than generating an empty struct type.
func (q *Queries) CountWidgets(ctx context.Context) (int64, error) {
	return 0, nil
}

func (q *Queries) GetWidget(ctx context.Context, id int64) (Widget, error) {
	return Widget{}, nil
}

type CreateWidgetParams struct {
	Name string
	Now  string
}

func (q *Queries) CreateWidget(ctx context.Context, arg CreateWidgetParams) (int64, error) {
	return 0, nil
}

type UpdateWidgetBasicsParams struct {
	Name string
	Now  string
	ID   int64
}

func (q *Queries) UpdateWidgetBasics(ctx context.Context, arg UpdateWidgetBasicsParams) error {
	return nil
}
`

// TestEmitActionsCompile builds a standalone module (replacing this
// repo, same pattern as sqlcrun_test.go's newScratchModule) containing
// EmitActions' output for the fixture plus the hand-written store stub
// above, and runs go build ./... in it — the brief's "emitted actions
// + a stub store package compile" requirement. No network: this is
// what makes it safe to run on every go test ./..., unlike
// TestRunSqlcGeneratesCompilingStore's real sqlc fetch.
func TestEmitActionsCompile(t *testing.T) {
	root := newScratchModule(t, false)
	genDir := filepath.Join(root, "gen")

	if _, _, err := EmitActions(root, genDir, fixtureResource()); err != nil {
		t.Fatalf("EmitActions(notes): %v", err)
	}
	if _, _, err := EmitActions(root, genDir, noAdvancedFixtureResource()); err != nil {
		t.Fatalf("EmitActions(widgets): %v", err)
	}

	writeStub := func(resource, content string) {
		t.Helper()
		dir := filepath.Join(genDir, "store", resource)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, "store.go"), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	writeStub("notes", stubNotesStore)
	writeStub("widgets", stubWidgetsStore)

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build ./... in scratch module: %v\n%s", err, out)
	}
}
