package generate

import (
	"html/template"
	"os"
	"path/filepath"
	"testing"

	"github.com/carlosframework/rastrillo"
	"github.com/carlosframework/rastrillo/ui"
)

// goldenListHTML is the brief's pinned golden for the fixture, with ONE
// binding amendment: the generated list renders Search only — no
// "Filter" key on list-bar and no filter control. (`filter` still
// validates on the manifest; declaring filter VALUES for a real
// dropdown is a later slice's job.)
const goldenListHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/notes/list.html and edit — generation of
     this one file then stops. */}}
{{define "content"}}
{{template "page-header" dict "Title" (T "resource.notes.name") "ActionHref" "/admin/notes/new" "ActionLabel" (T "ui.new")}}
{{if .Empty}}
{{template "empty-state" dict "Title" (T "resource.notes.empty.title") "Body" (T "resource.notes.empty.body") "ActionHref" "/admin/notes/new" "ActionLabel" (T "ui.new")}}
{{else}}
<div class="rst-list">
{{template "list-bar" dict "SearchAction" "/admin/notes" "Query" .Query "Placeholder" (T "ui.search") "Hidden" .Carry}}
{{range .Rows}}{{template "list-row-action" dict "Href" .Href "Main" .Main "Sub" .Sub}}
{{end}}
</div>
{{if .Pagination.Show}}{{template "pagination" dict "Items" .Pagination.Items}}{{end}}
{{end}}
{{end}}
`

// goldenShowHTML: page-header (record's first text field as Title, edit
// action pill) + detail-list over every declared field, in the fixture's
// columns() order (Title, Price, Body — List columns first, then Form
// fields not already present). Money (Price) renders Mono, since it is
// a formatted-currency string, not prose.
const goldenShowHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/notes/show.html and edit — generation of
     this one file then stops.

     Data contract (the action emitter reads this):
       Title     string, required — the record shown here (its first
                 text field's value; list.html's Main, restated for the
                 header)
       EditHref  string, required — this record's edit route
       Fields    map[string]string, required — every declared field's
                 value keyed by its declared name, in this resource's
                 declaration order: Title, Price, Body. Money is
                 already formatted as a dollar string by the action —
                 templates never do money math. */}}
{{define "content"}}
{{template "page-header" dict "Title" .Title "ActionHref" .EditHref "ActionLabel" (T "ui.edit")}}
{{template "detail-list" dict "Items" (list
  (dict "Label" (T "resource.notes.field.title") "Value" .Fields.Title)
  (dict "Label" (T "resource.notes.field.price") "Value" .Fields.Price "Mono" true)
  (dict "Label" (T "resource.notes.field.body") "Value" .Fields.Body)
)}}
{{end}}
`

// goldenFormHTML: New posts Basics+Advanced as one form to the create
// route (r.Route); Edit posts Basics to .BasicsAction and, because the
// fixture's Advanced is non-empty, a second form posts Advanced to
// .AdvancedAction. Money (Price) renders as field-text — templates
// never do money math, the action already formatted the value.
const goldenFormHTML = `{{/* Code generated by rastrillo generate; DO NOT EDIT.
     Eject: copy to templates/notes/form.html and edit — generation of
     this one file then stops.

     Data contract (the action emitter reads this):
       IsNew           bool, required — New renders one form posting
                       every field to the create route; Edit renders
                       Basics (and, when this resource declares
                       Advanced fields, a second Advanced form)
       Fields          map[string]string, required — current values
                       keyed by declared field name; Money already
                       formatted as a dollar string by the action
                       (templates never do money math); empty strings
                       for New
       Errors          map[string]string, optional — a validation
                       message per field name, set only on a 400
                       re-render
       BasicsAction    string, required when !IsNew — the
                       edit-basics POST target
       AdvancedAction  string, required when !IsNew — the
                       edit-advanced POST target */}}
{{define "content"}}
{{if .IsNew}}
<form class="rst-form" method="post" action="/admin/notes">
{{template "field-text" dict "Name" "Title" "Label" (T "resource.notes.field.title") "Value" .Fields.Title "Error" .Errors.Title}}
{{template "field-textarea" dict "Name" "Body" "Label" (T "resource.notes.field.body") "Value" .Fields.Body "Error" .Errors.Body}}
{{template "field-text" dict "Name" "Price" "Label" (T "resource.notes.field.price") "Value" .Fields.Price "Error" .Errors.Price}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/notes" "CancelLabel" (T "ui.cancel")}}
</form>
{{else}}
<form class="rst-form" method="post" action="{{.BasicsAction}}">
{{template "field-text" dict "Name" "Title" "Label" (T "resource.notes.field.title") "Value" .Fields.Title "Error" .Errors.Title}}
{{template "field-textarea" dict "Name" "Body" "Label" (T "resource.notes.field.body") "Value" .Fields.Body "Error" .Errors.Body}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/notes" "CancelLabel" (T "ui.cancel")}}
</form>
<form class="rst-form" method="post" action="{{.AdvancedAction}}">
{{template "field-text" dict "Name" "Price" "Label" (T "resource.notes.field.price") "Value" .Fields.Price "Error" .Errors.Price}}
{{template "form-foot" dict "Submit" (T "ui.save") "CancelHref" "/admin/notes" "CancelLabel" (T "ui.cancel")}}
</form>
{{end}}
{{end}}
`

func TestEmitTemplatesGoldenFiles(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	written, skipped, err := EmitTemplates(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}
	if len(skipped) != 0 {
		t.Fatalf("skipped = %v, want none", skipped)
	}
	wantWritten := []string{
		filepath.Join(genDir, "templates", "notes", "list.html"),
		filepath.Join(genDir, "templates", "notes", "show.html"),
		filepath.Join(genDir, "templates", "notes", "form.html"),
	}
	if len(written) != len(wantWritten) {
		t.Fatalf("written = %v, want %v", written, wantWritten)
	}
	for i := range wantWritten {
		if written[i] != wantWritten[i] {
			t.Errorf("written[%d] = %q, want %q", i, written[i], wantWritten[i])
		}
	}

	cases := []struct {
		path string
		want string
	}{
		{filepath.Join(genDir, "templates", "notes", "list.html"), goldenListHTML},
		{filepath.Join(genDir, "templates", "notes", "show.html"), goldenShowHTML},
		{filepath.Join(genDir, "templates", "notes", "form.html"), goldenFormHTML},
	}
	for _, c := range cases {
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != c.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", c.path, got, c.want)
		}
	}
}

func TestEmitTemplatesIsIdempotent(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	written, _, err := EmitTemplates(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitTemplates (1st): %v", err)
	}
	first := readAllFiles(t, written)

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates (2nd): %v", err)
	}
	second := readAllFiles(t, written)

	for _, p := range written {
		if first[p] != second[p] {
			t.Errorf("%s changed between runs", p)
		}
	}
}

func TestEmitTemplatesSkipsEjectedFiles(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	handDir := filepath.Join(appRoot, "templates", "notes")
	if err := os.MkdirAll(handDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(handDir, "list.html"), []byte("hand-written"), 0o644); err != nil {
		t.Fatal(err)
	}

	written, skipped, err := EmitTemplates(appRoot, genDir, r)
	if err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	wantSkipped := []string{filepath.Join(genDir, "templates", "notes", "list.html")}
	if len(skipped) != 1 || skipped[0] != wantSkipped[0] {
		t.Fatalf("skipped = %v, want %v", skipped, wantSkipped)
	}
	if _, err := os.Stat(filepath.Join(genDir, "templates", "notes", "list.html")); !os.IsNotExist(err) {
		t.Fatalf("list.html was written into genDir despite the hand file")
	}

	wantWritten := []string{
		filepath.Join(genDir, "templates", "notes", "show.html"),
		filepath.Join(genDir, "templates", "notes", "form.html"),
	}
	if len(written) != len(wantWritten) {
		t.Fatalf("written = %v, want %v", written, wantWritten)
	}
	for i := range wantWritten {
		if written[i] != wantWritten[i] {
			t.Errorf("written[%d] = %q, want %q", i, written[i], wantWritten[i])
		}
	}
}

// TestEmittedTemplatesParse proves the emitted files compile as
// templates in exactly the environment the app provides them: ui's
// partials plus ui.Funcs() (dict/list/icon), plus a stubbed T (the app
// binds the real one per locale at request time; see localemw.go).
func TestEmittedTemplatesParse(t *testing.T) {
	appRoot := t.TempDir()
	genDir := t.TempDir()
	r := fixtureResource()

	if _, _, err := EmitTemplates(appRoot, genDir, r); err != nil {
		t.Fatalf("EmitTemplates: %v", err)
	}

	tmpl := template.New("").Funcs(ui.Funcs()).Funcs(template.FuncMap{
		"T": func(s string) string { return s },
	})
	tmpl, err := tmpl.ParseFS(ui.Templates(), "*.html")
	if err != nil {
		t.Fatalf("parse ui templates: %v", err)
	}
	tmpl, err = tmpl.ParseGlob(filepath.Join(genDir, "templates", "notes", "*.html"))
	if err != nil {
		t.Fatalf("parse emitted templates: %v", err)
	}
	if tmpl.Lookup("content") == nil {
		t.Fatalf("no \"content\" template defined after parsing")
	}
}

func TestEmitTemplatesUnknownKindPanics(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("expected panic for unknown Kind")
		}
	}()
	r := fixtureResource()
	r.Form.Basics[0].Kind = rastrillo.Kind("bogus")
	_, _, _ = EmitTemplates(t.TempDir(), t.TempDir(), r)
}
